services:
  db:
    image: postgres:13 
    environment:
      POSTGRES_DB: mutant_detector
      POSTGRES_USER: vicky
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  
    networks:
      - mutant-network
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  api:
    build: .
    environment:
      POSTGRES_HOST: db  
      POSTGRES_PORT: 5432  
      POSTGRES_DB: mutant_detector 
      POSTGRES_USER: vicky  
      POSTGRES_PASSWORD: password  
    depends_on:
      - db
    ports:
      - "8000"
    networks:
      - mutant-network

networks:
  mutant-network:
    driver: bridge

volumes:
  postgres_data:
